kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibmcloud-image-enforcement
  labels:
    app: {{ template "cise.name" . }}
    chart: {{ template "cise.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups: ["securityenforcement.admission.cloud.ibm.com"]
  resources: ["imagepolicies", "clusterimagepolicies"]
  verbs: ["get", "watch", "list", "create"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "create", "delete"]
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["validatingwebhookconfigurations", "mutatingwebhookconfigurations"]
  verbs: ["get", "create", "delete"]
- apiGroups: [""]
  resources: ["secrets", "serviceaccounts"]
  verbs: ["get"]