apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: imagepolicies.portieris.cloud.ibm.com
  labels:
    app: portieris
spec:
  group: portieris.cloud.ibm.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                repositories:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      policy:
                        type: object
                        nullable: true
                        properties:
                          vulnerability:
                            type: object
                            properties:
                              ICCRVA:
                                type: object
                                properties:
                                  enabled:
                                    type: boolean
                                  account:
                                    type: string
                          trust:
                            type: object
                            properties:
                              enabled:
                                type: boolean
                              trustServer:
                                type: string
                              signerSecrets:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    name:
                                      type: string
                          simple:
                            type: object
                            properties:
                              storeURL:
                                type: string
                              storeSecret:
                                type: string
                              requirements:
                                type: array
                                nullable: true
                                items:
                                  type: object
                                  required: [ "type" ]
                                  properties:
                                    type:
                                      type: string
                                      enum: [ "insecureAcceptAnything", "reject", "signedBy" ]
                                    keySecret:
                                      type: string
                                    signedIdentity:
                                      type: object
                                      required: [ "type" ]
                                      properties:
                                        type:
                                          type: string
                                          enum: [ "matchExact", "matchRepository", "matchExactRepository", "matchExactReference", "remapIdentityy" ]
                                        dockerRepository:
                                          type: string
                                        dockerReference:
                                          type: string
                                        prefix:
                                          type: string
                                        signedPrefix: 
                                          type: string
  names:
    kind: ImagePolicy
    listKind: ImagePolicyList
    plural: imagepolicies
    singular: imagepolicy
  scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusterimagepolicies.portieris.cloud.ibm.com
  labels:
    app: portieris
spec:
  group: portieris.cloud.ibm.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                repositories:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      policy:
                        type: object
                        properties:
                          vulnerability:
                            type: object
                            properties:
                              ICCRVA:
                                type: object
                                properties:
                                  enabled:
                                    type: boolean
                                  account:
                                    type: string
                          trust:
                            type: object
                            properties:
                              enabled:
                                type: boolean
                              trustServer:
                                type: string
                              signerSecrets:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    name:
                                      type: string
                          simple:
                            type: object
                            properties:
                              storeURL:
                                type: string
                              storeSecret:
                                type: string
                              requirements:
                                type: array
                                nullable: true
                                items:
                                  type: object
                                  required: [ "type" ]
                                  properties:
                                    type:
                                      type: string
                                      enum: [ "insecureAcceptAnything", "reject", "signedBy" ]
                                    keySecret:
                                      type: string
                                    signedIdentity:
                                      type: object
                                      required: [ "type" ]
                                      enum: [ "matchExact", "matchRepository", "matchExactReference", "matchExactRepository", "remapIdentity" ]
                                      properties:
                                        type:
                                          type: string
                                        prefix:
                                          type: string
                                        signedPrefix: 
                                          type: string
                                        dockerReference:
                                          type: string
                                        dockerRepository:
                                          type: string
  names:
    kind: ClusterImagePolicy
    listKind: ClusterImagePolicyList
    plural: clusterimagepolicies
    singular: clusterimagepolicy
  scope: Cluster
