apiVersion: batch/v1
kind: Job
metadata:
  name: delete-admission-webhooks
  namespace: ibm-system
  annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-weight: "-10"
    helm.sh/hook-delete-policy: hook-succeeded
  labels:
    app: {{ template "portieris.name" . }}
    chart: {{ template "portieris.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  template:
    metadata:
      name: delete-admission-webhooks
      labels:
        app: {{ template "portieris.name" . }}
        chart: {{ template "portieris.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      serviceAccountName: portieris
      containers:
        - name: hyperkube
          image: "{{ .Values.hyperkube.repository }}:{{ .Values.hyperkube.tag }}"
          command:
            - /kubectl
            - delete
            - -f
            - /tmp/portieris/webhooks.yaml
            - --ignore-not-found=true
          volumeMounts:
            - mountPath: "/tmp/portieris"
              name: tmp-configmap-portieris
      volumes:
        - name: tmp-configmap-portieris
          configMap:
            name: admission-webhooks
      restartPolicy: OnFailure
