apiVersion: v1
name: portieris
version: 0.9.0next
description: Admission Controller webhook for enforcing image trust in your cluster
maintainer:
  - stuart.hayton@uk.ibm.com
  - jack.baines@uk.ibm.com
  - michaelh@uk.ibm.com
