apiVersion: v1
name: portieris
version: v0.13.30
description: Admission Controller webhook for enforcing image trust in your cluster
maintainers:
  - name: Stuart Hayton
    email: stuart.hayton@uk.ibm.com
  - name: Jack Baines
    email: jack.baines@uk.ibm.com
  - name: Michael Hough
    email: michaelh@uk.ibm.com
